name: Deploy to Azure Web App

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '22'
      build-command:
        type: string
        default: 'npm run build'
      app-name:
        required: true
        type: string
      package-path:
        required: true
        type: string
    secrets:
      azure-client-id:
        required: true
      azure-tenant-id:
        required: true
      azure-subscription-id:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: ${{ inputs.build-command }}

      - name: Prepare deployment package
        run: |
          cp package.json ${{ inputs.package-path }}/
          cd ${{ inputs.package-path }}
          npm install --omit=dev

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.azure-client-id }}
          tenant-id: ${{ secrets.azure-tenant-id }}
          subscription-id: ${{ secrets.azure-subscription-id }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ inputs.app-name }}
          package: ${{ inputs.package-path }}
